/** Names and ingredients from Browse Meal Ideas. Directions stay in the app catalog. */
export type BrowseIdea = { name: string; mealType: string; ingredients: string[] };

export const BROWSE_IDEAS: BrowseIdea[] = [
  { name: "Spaghetti and Meatballs", mealType: "dinner", ingredients: ["1 lb spaghetti","1 lb ground beef","1 egg","1/2 cup breadcrumbs","1 jar marinara sauce","Parmesan cheese"] },
  { name: "Baked Mac and Cheese", mealType: "dinner", ingredients: ["1 lb elbow macaroni","3 cups shredded cheddar","2 cups milk","3 tbsp butter","3 tbsp flour","1/2 cup breadcrumbs"] },
  { name: "Classic Cheeseburgers", mealType: "dinner", ingredients: ["1.5 lb ground beef","6 burger buns","6 slices cheddar","Lettuce","Tomato","Ketchup & mustard"] },
  { name: "Sheet Pan Chicken Fajitas", mealType: "dinner", ingredients: ["1.5 lb chicken breast","2 bell peppers","1 onion","Fajita seasoning","Tortillas","Sour cream"] },
  { name: "Meatloaf with Mashed Potatoes", mealType: "dinner", ingredients: ["2 lb ground beef","1 cup breadcrumbs","2 eggs","Ketchup glaze","4 potatoes","Butter & milk"] },
  { name: "Chicken Pot Pie", mealType: "dinner", ingredients: ["2 cups cooked chicken","1 cup peas & carrots","1 can cream of chicken soup","2 pie crusts"] },
  { name: "BBQ Pulled Pork Sandwiches", mealType: "dinner", ingredients: ["3 lb pork shoulder","1 bottle BBQ sauce","6 buns","Coleslaw mix"] },
  { name: "Baked Ziti", mealType: "dinner", ingredients: ["1 lb ziti pasta","1 jar marinara","15 oz ricotta","2 cups mozzarella","1 egg"] },
  { name: "Fried Chicken Tenders", mealType: "dinner", ingredients: ["1.5 lb chicken tenders","2 cups flour","2 eggs","Panko breadcrumbs","Oil for frying"] },
  { name: "Grilled Salmon with Asparagus", mealType: "dinner", ingredients: ["4 salmon fillets","1 bunch asparagus","Lemon","Olive oil","Garlic"] },
  { name: "Pot Roast with Root Vegetables", mealType: "dinner", ingredients: ["3 lb chuck roast","4 carrots","4 potatoes","1 onion","Beef broth"] },
  { name: "Shepherd's Pie", mealType: "dinner", ingredients: ["1.5 lb ground beef","2 cups mixed vegetables","4 potatoes","Butter & milk","Beef gravy"] },
  { name: "Chili con Carne", mealType: "dinner", ingredients: ["2 lb ground beef","2 cans kidney beans","1 can diced tomatoes","Chili powder","Onion"] },
  { name: "Grilled Steak with Baked Potatoes", mealType: "dinner", ingredients: ["4 steaks","4 russet potatoes","Butter","Sour cream","Chives"] },
  { name: "Buffalo Chicken Wraps", mealType: "dinner", ingredients: ["1.5 lb chicken breast","Buffalo sauce","Tortillas","Ranch dressing","Lettuce"] },
  { name: "Turkey Meatball Subs", mealType: "dinner", ingredients: ["1 lb ground turkey","Sub rolls","Marinara sauce","Mozzarella cheese"] },
  { name: "Loaded Baked Potato Bar", mealType: "dinner", ingredients: ["6 russet potatoes","Shredded cheese","Bacon bits","Sour cream","Chives","Broccoli"] },
  { name: "Homemade Pizza Night", mealType: "dinner", ingredients: ["Pizza dough","1 cup pizza sauce","2 cups mozzarella","Pepperoni","Toppings of choice"] },
  { name: "Roast Chicken with Vegetables", mealType: "dinner", ingredients: ["1 whole chicken","4 carrots","4 potatoes","1 onion","Olive oil","Herbs"] },
  { name: "Sloppy Joes", mealType: "dinner", ingredients: ["1.5 lb ground beef","Sloppy joe sauce","6 hamburger buns"] },
  { name: "Fish and Chips", mealType: "dinner", ingredients: ["1.5 lb cod fillets","2 cups flour","Beer or soda water","4 potatoes","Oil for frying"] },
  { name: "Turkey Chili", mealType: "dinner", ingredients: ["2 lb ground turkey","2 cans black beans","1 can diced tomatoes","Chili powder","Onion"] },
  { name: "Chicken Parmesan", mealType: "dinner", ingredients: ["4 chicken breasts","Breadcrumbs","Marinara sauce","Mozzarella cheese","Spaghetti"] },
  { name: "Beef Stroganoff", mealType: "dinner", ingredients: ["1.5 lb beef sirloin","8 oz mushrooms","Sour cream","Egg noodles","Beef broth"] },
  { name: "Grilled Cheese and Tomato Soup", mealType: "dinner", ingredients: ["8 slices bread","8 slices cheddar","Butter","1 can tomato soup"] },
  { name: "Honey Garlic Glazed Salmon", mealType: "dinner", ingredients: ["4 salmon fillets","Honey","Soy sauce","Garlic","Rice"] },
  { name: "Chicken and Dumplings", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Chicken broth","Carrots & celery","Biscuit dough","Frozen peas"] },
  { name: "Philly Cheesesteak Sandwiches", mealType: "dinner", ingredients: ["1.5 lb thinly sliced steak","Onion & bell pepper","Provolone cheese","Hoagie rolls"] },
  { name: "Baked BBQ Chicken Thighs", mealType: "dinner", ingredients: ["8 chicken thighs","BBQ sauce","Garlic powder","Paprika"] },
  { name: "Beef and Vegetable Skewers", mealType: "dinner", ingredients: ["1.5 lb beef sirloin, cubed","Bell peppers","Onion","Cherry tomatoes","Olive oil marinade"] },
  { name: "Creamy Chicken and Rice Casserole", mealType: "dinner", ingredients: ["2 cups cooked chicken","2 cups cooked rice","Cream of mushroom soup","Shredded cheese","Milk"] },
  { name: "Country Fried Steak", mealType: "dinner", ingredients: ["4 cube steaks","Flour","Eggs","Milk gravy","Mashed potatoes"] },
  { name: "Smothered Pork Chops", mealType: "dinner", ingredients: ["4 bone-in pork chops","Onion","Chicken broth","Cream of mushroom soup"] },
  { name: "Fluffy Pancakes", mealType: "breakfast", ingredients: ["2 cups flour","2 eggs","1.5 cups milk","2 tbsp sugar","Maple syrup"] },
  { name: "Scrambled Eggs and Bacon", mealType: "breakfast", ingredients: ["8 eggs","8 strips bacon","Butter","Salt & pepper"] },
  { name: "Belgian Waffles", mealType: "breakfast", ingredients: ["2 cups flour","2 eggs","1.75 cups milk","1/2 cup butter","Whipped cream"] },
  { name: "Breakfast Burritos", mealType: "breakfast", ingredients: ["6 eggs","Tortillas","Shredded cheese","Breakfast sausage","Salsa"] },
  { name: "Overnight Oats", mealType: "breakfast", ingredients: ["2 cups rolled oats","2 cups milk","Honey","Berries","Chia seeds"] },
  { name: "French Toast", mealType: "breakfast", ingredients: ["8 slices bread","4 eggs","1 cup milk","Cinnamon","Maple syrup"] },
  { name: "Veggie Omelet", mealType: "breakfast", ingredients: ["6 eggs","Bell pepper","Onion","Spinach","Shredded cheese"] },
  { name: "Breakfast Casserole", mealType: "breakfast", ingredients: ["8 eggs","Bread cubes","Breakfast sausage","Shredded cheese","Milk"] },
  { name: "Yogurt Parfaits", mealType: "breakfast", ingredients: ["Greek yogurt","Granola","Mixed berries","Honey"] },
  { name: "Breakfast Sandwiches", mealType: "breakfast", ingredients: ["English muffins","6 eggs","Cheese slices","Canadian bacon"] },
  { name: "Banana Pancakes", mealType: "breakfast", ingredients: ["2 ripe bananas","2 cups flour","2 eggs","1.5 cups milk"] },
  { name: "Cinnamon Rolls", mealType: "breakfast", ingredients: [] },
  { name: "Avocado Toast", mealType: "breakfast", ingredients: ["4 slices sourdough","2 avocados","Lemon juice","Red pepper flakes"] },
  { name: "Breakfast Potatoes and Sausage", mealType: "breakfast", ingredients: ["4 potatoes, diced","Breakfast sausage links","Onion","Bell pepper"] },
  { name: "Smoothie Bowls", mealType: "breakfast", ingredients: ["Frozen berries","1 banana","Greek yogurt","Granola topping"] },
  { name: "Breakfast Hash with Eggs", mealType: "breakfast", ingredients: ["4 potatoes, diced","Onion & bell pepper","4 eggs","Paprika"] },
  { name: "Blueberry Muffins", mealType: "breakfast", ingredients: ["2 cups flour","1 cup blueberries","2 eggs","1 cup milk","3/4 cup sugar"] },
  { name: "Ham and Cheese Crepes", mealType: "breakfast", ingredients: ["1 cup flour","2 eggs","1.5 cups milk","Ham slices","Swiss cheese"] },
  { name: "Breakfast Quesadillas", mealType: "breakfast", ingredients: ["6 eggs","Tortillas","Shredded cheese","Breakfast sausage or bacon"] },
  { name: "Shakshuka", mealType: "breakfast", ingredients: ["1 can crushed tomatoes","Onion & bell pepper","4 eggs","Cumin & paprika"] },
  { name: "Bagel with Cream Cheese and Lox", mealType: "breakfast", ingredients: ["4 bagels","Cream cheese","Smoked salmon","Red onion","Capers"] },
  { name: "Baked Oatmeal Cups", mealType: "breakfast", ingredients: ["2 cups rolled oats","2 eggs","1 cup milk","Mashed banana","Cinnamon"] },
  { name: "Sausage Gravy and Biscuits", mealType: "breakfast", ingredients: ["Biscuits","Breakfast sausage","Flour","Milk"] },
  { name: "Margherita Pizza", mealType: "dinner", ingredients: ["Pizza dough","Tomato sauce","Fresh mozzarella","Basil leaves","Olive oil"] },
  { name: "Fettuccine Alfredo", mealType: "dinner", ingredients: ["1 lb fettuccine","1 cup heavy cream","1 cup Parmesan","Butter","Garlic"] },
  { name: "Chicken Piccata", mealType: "dinner", ingredients: ["4 chicken cutlets","Capers","Lemon juice","White wine","Butter"] },
  { name: "Lasagna", mealType: "dinner", ingredients: ["Lasagna noodles","1 lb ground beef","Ricotta cheese","Marinara sauce","Mozzarella cheese"] },
  { name: "Risotto with Mushrooms", mealType: "dinner", ingredients: ["2 cups arborio rice","8 oz mushrooms","Chicken broth","Parmesan","White wine"] },
  { name: "Chicken Marsala", mealType: "dinner", ingredients: ["4 chicken breasts","8 oz mushrooms","Marsala wine","Butter","Flour"] },
  { name: "Caprese Salad with Grilled Chicken", mealType: "dinner", ingredients: ["2 chicken breasts","Fresh mozzarella","Tomatoes","Basil","Balsamic glaze"] },
  { name: "Minestrone Soup", mealType: "dinner", ingredients: ["Mixed vegetables","1 can cannellini beans","Small pasta","Vegetable broth","Parmesan rind"] },
  { name: "Stuffed Shells", mealType: "dinner", ingredients: ["Jumbo pasta shells","Ricotta cheese","Spinach","Marinara sauce","Mozzarella"] },
  { name: "Chicken Parmesan Sliders", mealType: "dinner", ingredients: ["Chicken tenders","Slider buns","Marinara sauce","Mozzarella slices"] },
  { name: "Penne alla Vodka", mealType: "dinner", ingredients: ["1 lb penne","Vodka sauce","Heavy cream","Parmesan"] },
  { name: "Eggplant Parmesan", mealType: "dinner", ingredients: ["2 eggplants","Breadcrumbs","Marinara sauce","Mozzarella","Parmesan"] },
  { name: "Italian Wedding Soup", mealType: "dinner", ingredients: ["Mini meatballs","Escarole or spinach","Chicken broth","Small pasta"] },
  { name: "Baked Chicken Parmesan Pasta", mealType: "dinner", ingredients: ["Chicken breast","Penne pasta","Marinara sauce","Mozzarella cheese"] },
  { name: "Tortellini with Pesto", mealType: "dinner", ingredients: ["Cheese tortellini","Pesto sauce","Cherry tomatoes","Parmesan"] },
  { name: "Chicken Cacciatore", mealType: "dinner", ingredients: ["4 chicken thighs","Bell peppers","Canned tomatoes","Onion","White wine"] },
  { name: "Spaghetti Carbonara", mealType: "dinner", ingredients: ["1 lb spaghetti","4 eggs","Pancetta or bacon","Parmesan cheese","Black pepper"] },
  { name: "Baked Rigatoni with Sausage", mealType: "dinner", ingredients: ["1 lb rigatoni","Italian sausage","Marinara sauce","Mozzarella cheese"] },
  { name: "Braised Short Ribs with Polenta", mealType: "dinner", ingredients: ["3 lb beef short ribs","Carrots & celery","Beef broth","Polenta"] },
  { name: "Caprese Panini", mealType: "lunch", ingredients: ["Ciabatta bread","Fresh mozzarella","Tomato","Basil","Balsamic glaze"] },
  { name: "Sausage and Peppers Pasta", mealType: "dinner", ingredients: ["1 lb pasta","Italian sausage","Bell peppers","Onion","Marinara sauce"] },
  { name: "Zuppa Toscana", mealType: "dinner", ingredients: ["Italian sausage","Potatoes","Kale","Chicken broth","Heavy cream"] },
  { name: "Chicken Milanese", mealType: "dinner", ingredients: ["4 chicken cutlets","Breadcrumbs","Eggs","Arugula salad","Lemon"] },
  { name: "Beef Tacos", mealType: "dinner", ingredients: ["1.5 lb ground beef","Taco seasoning","Taco shells","Lettuce","Shredded cheese","Salsa"] },
  { name: "Chicken Quesadillas", mealType: "dinner", ingredients: ["2 cups cooked chicken","Flour tortillas","Shredded cheese","Sour cream"] },
  { name: "Beef Burritos", mealType: "dinner", ingredients: ["1.5 lb ground beef","Rice","Refried beans","Tortillas","Shredded cheese"] },
  { name: "Chicken Enchiladas", mealType: "dinner", ingredients: ["2 cups cooked chicken","Corn tortillas","Enchilada sauce","Shredded cheese"] },
  { name: "Carne Asada", mealType: "dinner", ingredients: ["2 lb flank steak","Lime juice","Garlic","Cilantro","Tortillas"] },
  { name: "Shrimp Tacos", mealType: "dinner", ingredients: ["1.5 lb shrimp","Corn tortillas","Cabbage slaw","Lime crema"] },
  { name: "Chicken Tortilla Soup", mealType: "dinner", ingredients: ["2 cups cooked chicken","Diced tomatoes","Chicken broth","Tortilla strips","Avocado"] },
  { name: "Pork Carnitas", mealType: "dinner", ingredients: ["3 lb pork shoulder","Orange juice","Garlic","Cumin","Tortillas"] },
  { name: "Cheese Enchiladas", mealType: "dinner", ingredients: ["Corn tortillas","Shredded cheese","Red enchilada sauce","Onion"] },
  { name: "Chicken Fajita Bowls", mealType: "dinner", ingredients: ["Chicken breast","Rice","Bell peppers","Black beans","Corn"] },
  { name: "Taco Salad", mealType: "dinner", ingredients: ["1 lb ground beef","Lettuce","Tortilla chips","Shredded cheese","Salsa"] },
  { name: "Chiles Rellenos", mealType: "dinner", ingredients: ["Poblano peppers","Cheese","Eggs","Flour","Tomato sauce"] },
  { name: "Elote (Mexican Street Corn)", mealType: "side", ingredients: ["6 ears corn","Mayo","Cotija cheese","Chili powder","Lime"] },
  { name: "Chicken Chilaquiles", mealType: "breakfast", ingredients: ["Tortilla chips","Salsa verde","Shredded chicken","Fried eggs","Queso fresco"] },
  { name: "Vegetarian Burrito Bowls", mealType: "dinner", ingredients: ["Rice","Black beans","Corn","Bell peppers","Salsa","Guacamole"] },
  { name: "Chicken Mole", mealType: "dinner", ingredients: ["4 chicken thighs","Mole sauce","Chicken broth","Rice"] },
  { name: "Barbacoa Beef", mealType: "dinner", ingredients: ["3 lb beef chuck roast","Chipotle peppers","Garlic","Cumin","Tortillas"] },
  { name: "Sopes with Refried Beans", mealType: "lunch", ingredients: ["Masa harina","Refried beans","Shredded cheese","Lettuce","Salsa"] },
  { name: "Mexican Rice and Beans", mealType: "side", ingredients: ["Rice","Black or pinto beans","Tomato sauce","Onion & garlic","Cumin"] },
  { name: "Camarones a la Diabla (Spicy Shrimp)", mealType: "dinner", ingredients: ["1.5 lb shrimp","Dried chile sauce or hot sauce","Garlic","Butter","Rice"] },
  { name: "Chicken Tinga Tacos", mealType: "dinner", ingredients: ["2 cups cooked shredded chicken","Chipotle in adobo","Tomato sauce","Onion","Tortillas"] },
  { name: "Huevos Rancheros", mealType: "breakfast", ingredients: ["4 eggs","Corn tortillas","Salsa or ranchero sauce","Refried beans","Queso fresco"] },
  { name: "Mexican Street Corn Salad", mealType: "side", ingredients: ["4 cups corn kernels","Mayo","Cotija cheese","Lime","Chili powder"] },
  { name: "Chicken Fried Rice", mealType: "dinner", ingredients: ["3 cups cooked rice","2 chicken breasts","2 eggs","Frozen peas & carrots","Soy sauce"] },
  { name: "Beef and Broccoli", mealType: "dinner", ingredients: ["1.5 lb flank steak","1 head broccoli","Soy sauce","Garlic","Ginger"] },
  { name: "Chicken Teriyaki", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Teriyaki sauce","Rice","Steamed broccoli"] },
  { name: "Vegetable Lo Mein", mealType: "dinner", ingredients: ["Lo mein noodles","Mixed vegetables","Soy sauce","Sesame oil","Garlic"] },
  { name: "Shrimp Pad Thai", mealType: "dinner", ingredients: ["Rice noodles","1 lb shrimp","Bean sprouts","Eggs","Pad Thai sauce","Peanuts"] },
  { name: "Sesame Chicken", mealType: "dinner", ingredients: ["1.5 lb chicken breast","Sesame seeds","Soy sauce","Honey","Rice"] },
  { name: "Vegetable Fried Rice", mealType: "dinner", ingredients: ["3 cups cooked rice","Mixed vegetables","2 eggs","Soy sauce","Green onion"] },
  { name: "Korean Beef Bulgogi", mealType: "dinner", ingredients: ["1.5 lb thinly sliced beef","Soy sauce","Pear or apple","Garlic","Sesame oil","Rice"] },
  { name: "Chicken Pad See Ew", mealType: "dinner", ingredients: ["Wide rice noodles","Chicken breast","Chinese broccoli","Soy sauce","Eggs"] },
  { name: "Thai Green Curry", mealType: "dinner", ingredients: ["Chicken thighs","Green curry paste","Coconut milk","Bell peppers","Basil","Rice"] },
  { name: "Chicken Katsu", mealType: "dinner", ingredients: ["4 chicken cutlets","Panko breadcrumbs","Katsu sauce","Rice","Cabbage slaw"] },
  { name: "Vegetable Dumplings", mealType: "dinner", ingredients: ["Dumpling wrappers","Cabbage","Carrots","Ginger","Soy dipping sauce"] },
  { name: "Miso Soup with Tofu", mealType: "side", ingredients: ["Miso paste","Tofu","Seaweed","Green onion","Dashi stock"] },
  { name: "Orange Chicken", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Orange juice","Soy sauce","Rice vinegar","Rice"] },
  { name: "Chicken and Vegetable Stir Fry", mealType: "dinner", ingredients: ["Chicken breast","Mixed stir-fry vegetables","Soy sauce","Garlic","Rice"] },
  { name: "General Tso's Chicken", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Cornstarch","Soy sauce","Rice vinegar","Brown sugar"] },
  { name: "Mongolian Beef", mealType: "dinner", ingredients: ["1.5 lb flank steak","Cornstarch","Soy sauce","Brown sugar","Green onion"] },
  { name: "Vietnamese Chicken Banh Mi", mealType: "lunch", ingredients: ["2 chicken breasts","Baguette","Pickled carrots & radish","Cilantro","Mayo"] },
  { name: "Egg Drop Soup", mealType: "side", ingredients: ["Chicken broth","2 eggs","Cornstarch","Green onion"] },
  { name: "Sweet and Sour Chicken", mealType: "dinner", ingredients: ["1.5 lb chicken breast","Bell peppers","Pineapple chunks","Sweet and sour sauce"] },
  { name: "Chicken Satay Skewers", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Peanut sauce","Coconut milk","Curry powder"] },
  { name: "Beef Ramen Bowl", mealType: "dinner", ingredients: ["Ramen noodles","1.5 lb thinly sliced beef","Beef broth","Soft-boiled egg","Green onion"] },
  { name: "Vegetable Spring Rolls", mealType: "snack", ingredients: ["Spring roll wrappers","Cabbage","Carrots","Bean sprouts","Soy dipping sauce"] },
  { name: "Greek Chicken Souvlaki", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Lemon juice","Olive oil","Oregano","Pita bread","Tzatziki"] },
  { name: "Greek Salad with Grilled Chicken", mealType: "dinner", ingredients: ["2 chicken breasts","Cucumber","Tomatoes","Feta cheese","Kalamata olives"] },
  { name: "Falafel Wraps", mealType: "dinner", ingredients: ["Falafel mix or chickpeas","Pita bread","Tahini sauce","Cucumber","Tomato"] },
  { name: "Chicken Shawarma", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Shawarma spice blend","Pita bread","Garlic sauce","Pickles"] },
  { name: "Stuffed Grape Leaves", mealType: "side", ingredients: ["Grape leaves","Rice"] },
  { name: "Baked Cod with Tomatoes and Olives", mealType: "dinner", ingredients: ["4 cod fillets","Cherry tomatoes","Kalamata olives","Olive oil","Garlic"] },
  { name: "Chicken Gyros", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Pita bread","Tzatziki sauce","Tomato","Red onion"] },
  { name: "Mediterranean Quinoa Bowl", mealType: "dinner", ingredients: ["2 cups quinoa","Chickpeas","Cucumber","Feta cheese","Lemon dressing"] },
  { name: "Lamb Kofta Kebabs", mealType: "dinner", ingredients: ["1.5 lb ground lamb","Garlic","Cumin","Parsley","Pita bread"] },
  { name: "Hummus and Veggie Platter", mealType: "snack", ingredients: ["Hummus","Carrots","Cucumber","Bell pepper","Pita chips"] },
  { name: "Spanakopita (Spinach Pie)", mealType: "dinner", ingredients: ["Phyllo dough","Spinach","Feta cheese","Onion","Eggs"] },
  { name: "Mediterranean Baked Chicken Thighs", mealType: "dinner", ingredients: ["8 chicken thighs","Cherry tomatoes","Olives","Lemon","Oregano"] },
  { name: "Tabbouleh Salad", mealType: "side", ingredients: ["Bulgur wheat","Parsley","Tomato","Cucumber","Lemon juice"] },
  { name: "Moussaka", mealType: "dinner", ingredients: ["Eggplant","1.5 lb ground lamb or beef","Tomato sauce","Bechamel sauce","Cinnamon"] },
  { name: "Grilled Lamb Chops with Herbs", mealType: "dinner", ingredients: ["8 lamb chops","Rosemary & thyme","Garlic","Olive oil","Lemon"] },
  { name: "Za'atar Roasted Vegetables", mealType: "side", ingredients: [] },
  { name: "Butter Chicken", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Tomato sauce","Heavy cream","Garam masala","Basmati rice"] },
  { name: "Chicken Tikka Masala", mealType: "dinner", ingredients: ["1.5 lb chicken breast","Yogurt marinade","Tomato sauce","Cream","Basmati rice"] },
  { name: "Vegetable Samosas", mealType: "snack", ingredients: ["Samosa wrappers","Potatoes","Peas","Cumin & spices","Oil for frying"] },
  { name: "Chana Masala (Chickpea Curry)", mealType: "dinner", ingredients: ["2 cans chickpeas","Tomato sauce","Onion","Garam masala","Rice"] },
  { name: "Lentil Dal", mealType: "dinner", ingredients: ["2 cups red lentils","Onion","Garlic & ginger","Turmeric","Cumin"] },
  { name: "Chicken Biryani", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Basmati rice","Yogurt","Biryani spices","Fried onions"] },
  { name: "Palak Paneer", mealType: "dinner", ingredients: ["Paneer cheese","Spinach","Onion","Garlic & ginger","Cream"] },
  { name: "Tandoori Chicken", mealType: "dinner", ingredients: ["1.5 lb chicken drumsticks","Yogurt marinade","Tandoori spice mix","Lemon"] },
  { name: "Vegetable Curry", mealType: "dinner", ingredients: ["Mixed vegetables","Coconut milk","Curry powder","Onion","Rice"] },
  { name: "Garlic Naan and Curry Night", mealType: "dinner", ingredients: ["Naan bread","Butter","Garlic","Your choice of curry"] },
  { name: "Aloo Gobi (Potato and Cauliflower Curry)", mealType: "dinner", ingredients: ["Potatoes","Cauliflower","Turmeric & cumin","Onion","Tomato"] },
  { name: "Chicken Korma", mealType: "dinner", ingredients: ["1.5 lb chicken thighs","Yogurt","Cashews or almonds","Cream","Garam masala"] },
  { name: "Saag Aloo", mealType: "dinner", ingredients: ["Spinach","Potatoes","Onion","Garlic & ginger","Cumin"] },
  { name: "Vegetable Pakoras", mealType: "snack", ingredients: ["Chickpea flour"] },
  { name: "Egg Curry", mealType: "dinner", ingredients: ["8 hard-boiled eggs","Tomato sauce","Onion","Garam masala","Rice"] },
  { name: "Rajma (Kidney Bean Curry)", mealType: "dinner", ingredients: ["2 cans kidney beans","Tomato sauce","Onion","Garlic & ginger","Garam masala"] },
  { name: "Homemade Trail Mix", mealType: "snack", ingredients: ["Peanuts","Raisins","Chocolate chips","Pretzels"] },
  { name: "Apple Slices with Peanut Butter", mealType: "snack", ingredients: ["4 apples","Peanut butter"] },
  { name: "Ants on a Log", mealType: "snack", ingredients: ["Celery","Peanut butter","Raisins"] },
  { name: "Cheese and Crackers", mealType: "snack", ingredients: ["Cheese cubes","Crackers","Grapes"] },
  { name: "Homemade Popcorn", mealType: "snack", ingredients: ["Popcorn kernels","Butter","Salt"] },
  { name: "Roasted Broccoli", mealType: "side", ingredients: ["2 heads broccoli","Olive oil","Garlic","Parmesan"] },
  { name: "Garlic Mashed Potatoes", mealType: "side", ingredients: ["4 lb potatoes","Butter","Milk","Garlic","Sour cream"] },
  { name: "Mac and Cheese Bites", mealType: "snack", ingredients: ["Cooked macaroni","Cheddar cheese","Breadcrumbs","Eggs"] },
  { name: "Fruit Kabobs", mealType: "snack", ingredients: ["Strawberries","Pineapple","Grapes","Melon","Skewers"] },
  { name: "Homemade Granola Bars", mealType: "snack", ingredients: ["Rolled oats","Honey","Peanut butter","Dried fruit","Chocolate chips"] },
  { name: "Roasted Sweet Potato Wedges", mealType: "side", ingredients: ["4 sweet potatoes","Olive oil","Paprika","Salt"] },
  { name: "Caesar Salad", mealType: "side", ingredients: ["Romaine lettuce","Caesar dressing","Parmesan","Croutons"] },
  { name: "Deviled Eggs", mealType: "snack", ingredients: ["12 eggs","Mayonnaise","Mustard","Paprika"] },
  { name: "Fruit Smoothies", mealType: "snack", ingredients: ["Mixed frozen fruit","Yogurt","Milk or juice","Honey"] },
  { name: "Veggie Quesadillas", mealType: "snack", ingredients: ["Tortillas","Shredded cheese","Bell peppers","Corn"] },
  { name: "Baked Zucchini Chips", mealType: "snack", ingredients: ["3 zucchini, sliced thin","Breadcrumbs","Parmesan","Egg"] },
  { name: "Homemade Guacamole and Chips", mealType: "snack", ingredients: ["4 avocados","Lime","Onion","Cilantro","Tortilla chips"] },
  { name: "Roasted Brussels Sprouts", mealType: "side", ingredients: ["2 lb Brussels sprouts","Olive oil","Balsamic glaze","Salt & pepper"] },
  { name: "Peanut Butter Energy Bites", mealType: "snack", ingredients: ["Rolled oats","Peanut butter","Honey","Mini chocolate chips"] },
  { name: "Cucumber Bites with Hummus", mealType: "snack", ingredients: ["2 cucumbers","Hummus","Cherry tomatoes","Paprika"] },
  { name: "Cornbread", mealType: "side", ingredients: ["Cornmeal","Flour","Milk","Eggs","Butter"] },
  { name: "Coleslaw", mealType: "side", ingredients: ["Shredded cabbage","Carrots","Mayo","Vinegar","Sugar"] },
  { name: "Roasted Corn Salad", mealType: "side", ingredients: ["4 cups corn kernels","Bell pepper","Red onion","Lime juice","Cilantro"] },
  { name: "Turkey Club Sandwich", mealType: "lunch", ingredients: ["Bread","Turkey slices","Bacon","Lettuce & tomato","Mayo"] },
  { name: "Chicken Caesar Wrap", mealType: "lunch", ingredients: ["2 chicken breasts","Romaine lettuce","Caesar dressing","Parmesan","Tortillas"] },
  { name: "Cobb Salad", mealType: "lunch", ingredients: ["Mixed greens","Grilled chicken","Bacon","Hard-boiled eggs","Blue cheese","Avocado"] },
  { name: "Tomato Basil Soup", mealType: "lunch", ingredients: ["Canned tomatoes","Vegetable broth","Heavy cream","Fresh basil","Garlic"] },
  { name: "BLT Sandwich", mealType: "lunch", ingredients: ["Bread","Bacon","Lettuce","Tomato","Mayo"] },
  { name: "Egg Salad Sandwich", mealType: "lunch", ingredients: ["8 hard-boiled eggs","Mayo","Mustard","Celery","Bread"] },
  { name: "Chicken Salad Croissants", mealType: "lunch", ingredients: ["2 cups cooked chicken, diced","Mayo","Grapes","Celery","Croissants"] },
  { name: "Veggie Hummus Wrap", mealType: "lunch", ingredients: ["Tortillas","Hummus","Cucumber","Bell pepper","Spinach"] },
  { name: "Turkey and Avocado Wrap", mealType: "lunch", ingredients: ["Tortillas","Turkey slices","Avocado","Lettuce","Ranch dressing"] },
  { name: "Ham and Swiss Panini", mealType: "lunch", ingredients: ["Bread","Ham slices","Swiss cheese","Mustard","Butter"] },
  { name: "Greek Chicken Pita Pockets", mealType: "lunch", ingredients: ["2 chicken breasts","Pita bread","Cucumber & tomato","Tzatziki"] },
  { name: "Southwest Chicken Salad", mealType: "lunch", ingredients: ["2 chicken breasts","Mixed greens","Black beans","Corn","Southwest dressing"] },
  { name: "Tuna Salad Sandwich", mealType: "lunch", ingredients: ["Canned tuna","Mayo","Celery","Bread","Lettuce"] },
  { name: "Caprese Sandwich", mealType: "lunch", ingredients: ["Ciabatta bread","Fresh mozzarella","Tomato","Basil","Balsamic glaze"] },
  { name: "Buffalo Chicken Salad", mealType: "lunch", ingredients: ["2 chicken breasts","Buffalo sauce","Mixed greens","Celery","Ranch dressing"] },
  { name: "Asian Sesame Noodle Salad", mealType: "lunch", ingredients: ["Noodles","Shredded carrots & cabbage","Sesame oil","Soy sauce","Peanuts"] },
  { name: "Loaded Baked Potato Soup", mealType: "lunch", ingredients: ["4 potatoes","Chicken broth","Milk","Cheddar cheese","Bacon bits"] },
  { name: "Chicken Noodle Soup", mealType: "lunch", ingredients: ["2 cups cooked chicken","Egg noodles","Carrots & celery","Chicken broth"] },
  { name: "Black Bean and Corn Salad", mealType: "lunch", ingredients: ["2 cans black beans","Corn","Bell pepper","Lime juice","Cilantro"] },
  { name: "Mediterranean Chickpea Salad", mealType: "lunch", ingredients: ["2 cans chickpeas","Cucumber","Tomato","Feta cheese","Lemon dressing"] },
];
